fixing build issue
this was caused by commit f9fbf34876f15daa23e49bea807ff0da8480756d

addressing:
error: Installed (but unpackaged) file(s) found:
   /usr/share/katello/lib/notifications/controller_helper.rb
   /usr/share/katello/lib/notifications/notifier.rb