add rubygem-po_to_json to foreman comps
addressing:
Error: Package: rubygem-gettext_i18n_rails_js-0.0.8-1.fc18.noarch (katello-foreman)
           Requires: rubygem(po_to_json) >= 0.0.7