Fixes #5989 - Fixing puppet repo sync check BZ1102826
There's some places we call 'puppet?' on ContentViewPuppetEnvironments so we
get the following error in the publish code.

NoMethodError: undefined method `puppet?' for
/usr/local/rvm/gems/ruby-1.9.3-p448@foreman/gems/activemodel-3.2.18/lib/active_model/attribute_methods.rb:407:in
`method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p448@foreman/gems/activerecord-3.2.18/lib/active_record/attribute_methods.rb:149:in
`method_missing'
/home/thomasmckay/code/katello/app/lib/actions/katello/repository/node_metadata_generate.rb:21:in
`block in plan'