require converge-ui-devel >- 0.7 for building
addressing:
   create public/stylesheets/compiled/widgets/tipsy_custom.css
    error app/stylesheets/sections/tabs.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/sections/tabs.css
    error app/stylesheets/sections/systems.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/sections/systems.css
   create public/stylesheets/compiled/sections/orgs.css
   create public/stylesheets/compiled/sections/operations.css
   create public/stylesheets/compiled/sections/notifications.css
    error app/stylesheets/sections/loginpage.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/sections/loginpage.css
    error app/stylesheets/sections/generic.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/sections/generic.css
    error app/stylesheets/sections/dashboard.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/sections/dashboard.css
    error app/stylesheets/sections/contents.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/sections/contents.css
   create public/stylesheets/compiled/print.css
    error app/stylesheets/katello.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/katello.css
    error app/stylesheets/ie.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/ie.css
    error app/stylesheets/fancyqueries.scss (Line 3: File to import not found or unreadable: converge-ui/vars.
Load paths:
  /tmp/spacewalk-build/rpmbuild-katello-7faede362d5bb573b3e5e8d9f47871fa348bfdd6lFGN_Q/BUILD/katello-git-21.7faede3/app/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/blueprint/stylesheets
  /usr/share/gems/gems/compass-0.11.5/frameworks/compass/stylesheets
  /usr/share/gems/gems/compass-960-plugin-0.10.4/stylesheets
  Compass::SpriteImporter)
   create public/stylesheets/compiled/fancyqueries.css
error: Bad exit status from /var/tmp/rpm-tmp.HQAstX (%build)