add rubygem-activesupport to rhel6 repo
addressing:
Error: Package: rubygem-delayed_job-2.1.4-2.el6.noarch (katello)
           Requires: rubygem(activesupport) >= 3.0
           Installing: 1:rubygem-activesupport-2.3.8-2.el6.noarch (epel)
               rubygem(activesupport) = 2.3.8