fixes #15184 - resolve several errors in MigrateContentHosts
This commit fixes several errors that were observed
in the migration while testing:
- undefined method 'org'
- Could not find the source association(s) :content_facets
- PG::Error: ERROR:  update or delete on table "katello_systems"
  violates foreign key constraint "smart_proxies_content_host_id_fk"
- ...

(cherry picked from commit 15e2016c12676cf9a8898c029dd1b32471475414)