Fixes #16441 - resolve upgrade uninitialized constant (#6304)
This resolves the error:
NameError: uninitialized constant Api::V2::Rendering
that was seen on a prod install
(cherry picked from commit a812f1f1a52d0da71ae73e627bf92f6b94748546)