add rubygem-rkerberos to foreman comps
addressing:
Error: Package: foreman-proxy-1.2.9999-1.201306071242gitc4a245d.fc18.noarch (katello-foreman)
           Requires: rubygem(rkerberos)