add rubygem-gettext_i18n_rails to foreman comps for F18
addressing:
Error: Package: rubygem-gettext_i18n_rails_js-0.0.8-1.fc18.noarch (katello-foreman)
           Requires: rubygem(gettext_i18n_rails) >= 0.7.1
           Installed: rubygem-gettext_i18n_rails-0.6.6-2.fc18.noarch (@updates)
               rubygem(gettext_i18n_rails) = 0.6.6
           Available: rubygem-gettext_i18n_rails-0.6.6-1.fc18.noarch (fedora)
               rubygem(gettext_i18n_rails) = 0.6.6

adding just to F18, because we already have it in el6. And in F19 is rubygem-gettext_i18n_rails-0.9.4-1.fc19 which is >= 0.7.1.