f18 - making apipie happy during build phase
Resolving:

undefined method `options' for Sass::Plugin:Module
/builddir/build/BUILD/katello-git-636.f7a2a30/config/environments/production.rb:59:in
`block in <top (required)>'
/usr/share/gems/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:24:in
`class_eval'
/usr/share/gems/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:24:in
`configure'

http://koji.katello.org/koji/getfile?taskID=22750&name=build.log

Also disabling apipie temporarily.