BZ #1771937 - Creating a new product by limited permissions user fails  with error "NoMethodError: undefined method `[]' for nil:NilClass"
Fixes #28413 - Create product with permissions (#8458)

This commit relaxes a permission requirement to create custom
products. Prior to this commit the custom product create required a user
do to have create_products, edit_products, and view_subscriptions.
However it is not entirely clear to the user that view_subscriptions is
needed to create a product. Since unlimited subscriptions happens to be
a side effect of Product creation, it makes sense for create/edit
products to be permission enough.

This commit precludes the need for view_subscriptions to create
unlimited subscription on product create.

(cherry picked from commit 7132721109753672327386f9c5bce441ae0020eb)