860952 - update Pool::find to not treat response as an array
This is a small change to revert a regression from an earlier commit.
The earlier commit introduced Util::Data::array_with_indifferent_access
to handle candlepin responses that contained multiple elements.  Pool::find
was updated with this change; however, in that api we are only requesting
a single pool; therefore, the following error would be generated:

	undefined method `with_indifferent_access' for
	["attributes", []]:Array (NoMethodError)
(cherry picked from commit 4389d552515e917e79bd680097cf90bcec1dedc2)