Refs #33292 - fix error message when import attribute is missing
Otherwise you get the following error:

    undefined local variable or method `import_attributes' for #<Katello::Api::V2::RepositoriesController:0x000055ecb351d600>
    Did you mean?  import_attribute

Or, fixing that:

    wrong number of arguments (given 2, expected 1)

Instead of e.g. "ostree_repository_name is required"

(cherry picked from commit 9e6333a9ffa881cf00102fc862a85f04909dbebc)