add rubygem-highline to foreman rhel6 comps
addressing:
Error: Package: 1:foreman-installer-1.2.9999-1.201306131832git8728197.el6.noarch (katello-foreman)
           Requires: rubygem-highline