make bundler happy
addressing:
tito build --test --rpm
....
+ echo Generating API docs
Generating API docs
+ rm -f Gemfile.lock
+ cp Gemfile Gemfile.old
+ echo 'gem "redcarpet"'
+ rake apipie:static RAILS_ENV=apipie --trace
rake aborted!
https://github.com/ruport/ruport (at master) is not checked out. Please run `bundle install`
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/source.rb:572:in `rescue in load_spec_files'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/source.rb:570:in `load_spec_files'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/source.rb:385:in `local_specs'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/source.rb:555:in `specs'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/definition.rb:356:in `block in converge_locked_specs'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/definition.rb:345:in `each'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/definition.rb:345:in `converge_locked_specs'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/definition.rb:143:in `resolve'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/definition.rb:90:in `specs'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/definition.rb:135:in `specs_for'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/definition.rb:124:in `requested_specs'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/environment.rb:23:in `requested_specs'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler/runtime.rb:11:in `setup'
/usr/share/gems/gems/bundler-1.0.21/lib/bundler.rb:110:in `setup'
/tmp/tito-build/rpmbuild-katello-885ebf776fc81fc0900ee1641a9670b950f9a193fZrd1f/BUILD/katello-git-374.885ebf7/config/boot.rb:8:in `<top (required)>'
/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/tmp/tito-build/rpmbuild-katello-885ebf776fc81fc0900ee1641a9670b950f9a193fZrd1f/BUILD/katello-git-374.885ebf7/config/application.rb:1:in `<top (required)>'
/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/usr/share/rubygems/rubygems/custom_require.rb:36:in `require'
/tmp/tito-build/rpmbuild-katello-885ebf776fc81fc0900ee1641a9670b950f9a193fZrd1f/BUILD/katello-git-374.885ebf7/Rakefile:4:in `<top (required)>'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `block in load_rakefile'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/share/gems/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/usr/bin/rake:32:in `<main>'
error: Bad exit status from /var/tmp/rpm-tmp.6fYaSZ (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.6fYaSZ (%build)

ERROR: Error running command