Fixes #34209 - unset sync_policy for repository mirrors
pulp_rpm has deprecated the `mirror` parameter in favor of
`sync_policy=mirror_complete`, but the other Pulpcore plugins don't yet
support `sync_policy`.

When setting both, pulp_rpm raises an error:

    Cannot use 'mirror' and 'sync_policy' options simultaneously. The 'mirror' option is deprecated, please use 'sync_policy' only.

But replacing mirror with sync_policy globally raises:

    Error: `sync_policy` is not a valid attribute in `PulpContainerClient::RepositorySyncURL`. Please check the name to make sure it's valid. List of attributes: [:remote, :mirror]

As `mirror` is still supported by all plugins, let's keep that and just
drop the `sync_policy` for now.

(cherry picked from commit aa6720c8bc8ed5a4b4de4370a3b050e9cbee2ba6)