add ruby193-rubygem-po_to_json to comps-katello-foreman-server-rhel6
addressing:
Error: Package: ruby193-rubygem-gettext_i18n_rails_js-0.0.8-1.el6.noarch (katello-foreman)
           Requires: ruby193-rubygem(po_to_json) >= 0.0.7