Revert "Fixes orcharhino logo issue since foreman uses react for layouting"
This reverts commit 692a3ccf01859b0e0f92bb1e4e5ece36738b7dcd.

Revert for now since it causes the following error during build:

NameError: uninitialized constant Katello::ApplicationController::OrcharhinoCore