fixes #20580 - error listing host collections on a host
Without this change, the user will observe an error when listing
the host collections associated with a content host:

2017-08-14T16:45:00 922f5a3b [app] [E] NoMethodError:
  undefined method `order' for #<Array:0x007f494d5162b8>
 | katello/api/v2/api_controller.rb:74:in `scoped_search'
 | katello/api/v2/host_collections_controller.rb:37:in `index'

Similar should also occur for listing host collections associated
with an activation key.

Cause was that the object returned for those cases was
a 'CollectionProxy', which will be converted to an Array
when 'uniq' is invoked on it.