add rubygem(rspec-core) to rhel6 comps as devel deps
addressing:
yum install katello-devel-all
...
--> Finished Dependency Resolution
Error: Package: rubygem-rspec-rails-2.6.1-7.el6.noarch (katello)
           Requires: rubygem(rspec-core) < 2.7
Error: Package: rubygem-rspec-rails-2.6.1-7.el6.noarch (katello)
           Requires: rubygem(rspec-core) >= 2.6.0
 You could try using --skip-broken to work around the problem