870456 - existing orgs do not get default value for system_info_keys in database
if you hit an error similar to this:
    NoMethodError: You have a nil object when you didn't expect it!
    You might have expected an instance of Array.
    The error occurred while evaluating nil.each
    /home/tomckay/code/katello/src/app/models/system.rb:230:in
    `init_default_custom_info_keys'
it means you had at least one org that existed prior to default system
info keys.

run 'rake db:migrate:redo VERSION=20120924211134' to undo the
system_info_keys migration and correct apply the new column to all
pre-existing organizations.

If any of your organizations had any information in the system_info_keys
column, unfortunately it will be removed.