add new dependencies for client
addressing:
yum upgrade katello-agent
...
--> Finished Dependency Resolution
Error: Package: katello-agent-1.3.1-1.git.476.f8f2f08.fc18.noarch (katello)
           Requires: python-pulp-agent-lib >= 2.0.5
Error: Package: katello-agent-1.3.1-1.git.476.f8f2f08.fc18.noarch (katello)
           Requires: pulp-rpm-handlers >= 2.0.5
 You could try using --skip-broken to work around the problem