Do not use two %s in translation string
Introduced in commit b435a7a2.
Two %s are hard to translate.
Addressing:
Found 1 malformed strings
app/models/glue/provider.rb: _("Subscription manifest %s for provider '%s' failed") %
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.E0AL96 (%build)
    Bad exit status from /var/tmp/rpm-tmp.E0AL96 (%build)

Additionally building string from two translated strings are very often hard for translators
to manage.
See BZ 886718 for example of such case.