fix incorrect argument
addressing:
  File "../src/katello/client/core/system_group.py", line 108, in setup_parser
    opt_parser_add_org(parser, required)
NameError: global name 'required' is not defined