fixes #17129 - allow deletion of cv & version associated w/ hg
This commit contains changes to allow deletion of a content
view version and view that has associations to a hostgroup
via the content view and media (synced content) settings.

Without it,
- deleting a version would show:

ERROR: update or delete on table "katello_repositories"
violates foreign key constraint
"hostgroups_kickstart_repository_id_fk"
on table "hostgroups" DETAIL: Key (id)=(25) is still
referenced from table "hostgroups"

- deleting a view would show:

Cannot delete record because of dependent hostgroups

(cherry picked from commit 6025e0de42508e71dee36369c9722922e0b84ec7)