Fix apipie documentation for systems
With update of apipie, the code that was not run before is now run in
runtime, causing troubles starting the production environmnet:

```
undefined method `params' for Hash:Apipie::Validator::HashValidator
/app/controllers/katello/api/v2/systems_controller.rb:397:in `block (2
levels) in <class:SystemsController>'
```