fixes #39258 - Unable to save host configuration due to missing variant_repos method
Fix for an issue where the entity.operatingsystem object doesn't provide the variant_repos method by checking to see it if exists, first.

This fixes a bug that prevents the user from being able to save changes made to a Debian or Ubuntu host with the message:

```
Failed to render template 'Preseed default', error: undefined method 'variant_repos' for #<Debian id: .............
```