Fixes #23942 - Reset Pool model after migration
The ::Katello::Pool model changed between 3.6 and 3.7 due to the
Candlepin 2.2 -> 2.3 migration. However the migration script does
not properly reset the column information after associating the
organization to the Pool.
This causes all sorts of foreign key violation errors like
"Error deleting manifest. PG::UniqueViolation:
ERROR: duplicate key value violates unique constraint
"index_katello_pools_on_cp_id""
when re indexing stuff from candlepin