fixes #19971 - allow repo create by non-admin and fix delete
Attempting to create a repository as a non-admin user would
generate the following error:

RuntimeError: Could not find a smart proxy with pulp feature.
 | .../smart_proxy_extensions.rb:60:in `default_capsule!'

Since we do not want to now require the user to have
an additional permission on smart proxies, we chose
to treat the default capsule as an unscoped query.

Also, observed that the UI behavior for the repository
deletion permissions was incorrect.  It was treating the
repo behavior based upon the product, which is determined
by all repos in that product vs the one the user is
working with.